Change update dependencies script so that it commits package-lock.json

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -1,27 +1,48 @@
-# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
-# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
-
-name: Node.js Package
-
+name: Update Dependencies
 on:
-  push:
-    branches:
-      - main
+  schedule:
+  - cron: 0 0 * * 6
+
+permissions:
+  contents: write
+  pull-requests: write
 
 jobs:
-  publish-npm:
+  update-dependencies:
     runs-on: ubuntu-latest
+    env:
+      HUSKY: 0
+    
+    strategy:
+      matrix:
+        node-version: [22.x]
+
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          registry-url: https://registry.npmjs.org/
-      - name: Install dependencies
-        run: npm ci
-      - name: Build package
-        run: npm run build
-      - name: Publish to npm
-        run: npm publish --access public
-        env:
-          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
+    - uses: actions/checkout@v4
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v4
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: "npm"
+    - name: Setup GitHub user
+      run: |
+        git config --global user.name "AlexUpBot"
+        git config --global user.email "alexupbot@bot.com"
+    - name: Update dependencies
+      run: |
+        cp package-lock.json package-lock-backup.json
+        npx npm-check-updates -u
+        if ! npm install; then
+          echo "npm install failed, restoring lockfile"
+          mv package-lock-backup.json package-lock.json
+        else
+          rm -f package-lock-backup.json
+        fi
+    - name: Create Pull Request
+      uses: peter-evans/create-pull-request@v6
+      with:
+        token: ${{ secrets.PAT_GITHUB }}
+        branch: update-dependencies
+        base: main
+        commit-message: Update dependencies
+        title: "Update dependencies"
